version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lifecaller-postgres
    environment:
      POSTGRES_DB: lifecaller
      POSTGRES_USER: lifecaller
      POSTGRES_PASSWORD: lifecaller123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lifecaller-net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: lifecaller-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lifecaller-net
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  lifecaller-net:
    driver: bridge